//POST REQUEST
export const POST_LOGIN = 'POST_LOGIN';
export const LOADING_LOGIN = 'LOADING_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN'

//ERROR HANDLING
export const ERROR_HANDLING = 'ERROR_HANDLING';